name: kfar-marketplace-coming-soon
region: fra
static_sites:
- build_command: echo "No build required"
  catchall_document: index.html
  environment_slug: html
  error_document: index.html
  index_document: index.html
  name: coming-soon
  output_dir: /
  routes:
  - path: /
domains:
- domain: kfarmarket.com
  type: PRIMARY
  zone: kfarmarket.com
